### ISSUE TITLE
 Making IMX Accessible to Everyone!

### ISSUE THREAD

**Issue by csking91** [immutable/imx-docs#50]
### Are you sure it's a bug?

- [X] Yes, it looks like a bug

### Is there an existing issue for this bug?

- [X] I have searched existing issues, and this bug hasn't been reported yet

### Issue description

Dear boys ,

With the era we are living in regarding the use of crypto and living and exploring the metaverses, IMX is gaining strength through their resources to bring as many people into this industry. My question is as simple as the solution is, to let more people enter the IMX network, you have to make a difference, you have to make the transition to IMX and all its projects even easier. For info etc do not hesitate to contact me. Good luck

**Comment by ckailash** [comment]
Hi @csking91 - thanks for raising an issue. I'm unclear on what the actual bug is here? For your reference, this repository exists to open-source our documentation and to collaborate on it with the broader Immutable Community. We have a [clear and accessible contributors guide](https://docs.x.immutable.com/docs/contributing). Is there anything else you're expecting? 

I'll be closing this ticket since it doesn't have any actionable bugs.

**Comment by csking91** [comment]
Hi @ckailash I apologize for the delay.
I understand that there are all the guides but for those who want to actively collaborate especially through the discord group it is quite complicated to find their way. Example for what concerns me I'm waiting to take the quizzes to become OG but at the moment still nothing and several months have passed. it could be meaning to insert a guide with all the steps to make careers in IMX even for people less skilled than a DEV.
